### ISSUE TITLE
Newest ViennaTalk-mac.dmg killed my iMac Pro

### ISSUE THREAD

**Issue by shinsahara** [tomooda/ViennaTalk#1]
After double click  ViennaTalk-mac.dmg iMac display blacked out.
Then, restart.

My environment is following:
macOS Mojave version 10.14.4
iMac Pro (2017)
processor: 3 GHz Intel Xeon W
memory: 64 GB 2666 MHz DDR4

**Comment by shinsahara** [comment]
On my MacBook Pro (15-inch, 2018), I've succeeded to install from  ViennaTalk-mac.dmg under macOS Mojave version 10.14.4.

**Comment by tomooda** [comment]
Good to know. I also found that some anti-virus software crashes macOS when launching ViennaTalk. Anyway, thanks for the report.
