### ISSUE TITLE
Meet trouble in "Print It" Japanese characters on [Graz] Prebuilt packages for Mac. 

### ISSUE THREAD

**Issue by shinsahara** [tomooda/ViennaTalk#10]
Meet trouble in "Print It" Japanese characters in Workspace.
But, it is OK in Pharo's Plaground.

<img width="727" alt="Screen Shot 2022-05-07 18 21 31" src="https://user-images.githubusercontent.com/8341396/167248043-653021c0-5061-425d-896a-1683e503e917.png">

**Comment by tomooda** [comment]
now fixed. :-) https://github.com/tomooda/ViennaTalk/releases/download/graz1/ViennaTalk-mac-x64.dmg
thank you for the report!
