### ISSUE TITLE
Japanese character displaying problem.

### ISSUE THREAD

**Issue by shinsahara** [tomooda/ViennaTalk#5]
I'll translate the following Japanese sentences into English within a few days.

# 日本語文字表示が文字化けする。

### ハードウェア
- 	 iMac Pro (2017)
- 	プロセッサ名:	10コアIntel Xeon W
- 	メモリ:	64 GB
### OS
- macOS 12.2.1

	
## ViennaTalkのインストール方法
 using` the following command on a shell

` curl https://raw.githubusercontent.com/tomooda/ViennaTalk/main/scripts/`

## ViennaTalkの日本語表示設定
Setting Browserを開き、Fontを"System Font Regular 10"に設定し、
Font for font画面で、“Update” ボタンを押した。
しかし、次に同じ Font for **font画面を開くと、**フォントがEnglishになったまま**である。
<img width="1041" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/8341396/155038838-b2e8f089-b723-4a36-81cb-94f0678d5ce4.png">

## 日本語入力
VDM Browserで "日本語" と入力すると**文字化けが起こる**が、文字化けしている部分をmacOSのメモにコピペすると、 "日本
<img width="454" alt="VDM Browser" src="https://user-images.githubusercontent.com/8341396/155038847-f8723cf0-360d-4920-a3bc-ca92bbc0ba1d.png">
語”と表示されるので、VDM Browserの文字表示がおかしいと考えられる。

**Comment by tomooda** [comment]
font dialogでOKボタン押しましたか？その後、Force allボタンを押しましたか？
フォントは何を選択しましたか？

**Comment by shinsahara** [comment]
あ、SystemFontにせよと言われたので、そうしていましたが、日本語フォント"Source Han Code JP N Regular 10"とかにしたら表示できました :-)

**Comment by tomooda** [comment]
よかった。Facebookで書いた「フォント選択時にUpdateボタンを押してシステムフォントの読み込みを忘れずに。」というのは、システム(OS)側が持っているフォントをPharo側に認識させる、という意味でした。なんにせよ、解決したようで、なにより。:smile:

**Comment by shinsahara** [comment]
ありがとうございました :-)
明日以降、Parallels上のWindows 10でトライしてみますね。
